package jp.co.sohtamei.crcmddpcc

data class Param(
    var pcode: Int = 0,
    var ccDp: Boolean = false,
    var datatype: PTP_DT = PTP_DT.UNDEF,
    var modeRw: ModeRW = ModeRW.Invalid,
    var current: Long = 0,
    var formflag: Formflag = Formflag.None,
    var enums: MutableList<Long> = mutableListOf(),

    var currentIndex: Int = 0,
)

enum class TypeIncDec {
    Inc,
    Dec,
    Min,
    Max
}

enum class ModeRW {
    Invalid,
    R,
    RW
}

enum class Formflag(val raw: Int) {
    None(0),
    Range(1),
    Enum(2);

    companion object { fun fromRaw(v: Int) = entries.firstOrNull { it.raw == v } ?: None }
}

enum class ModeInput {
    Disabled,
    CC,
    DP
}

val ccParams: MutableList<Param> = mutableListOf(
  //Param(\1, \2, PTP_DT.\3, formflag = Formflag.\4, enums = mutableListOf(\5)),
  //Param\(pcode:(.*), cc_dp:(.*), datatype:\.(.*), formflag:\.(.*), enums:\[(.*)\]\),
    Param(0xD2C2, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2C3, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2C8, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2C9, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2CD, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2CE, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2CF, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2D0, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2D1, true, PTP_DT.INT16, formflag = Formflag.Range, enums = mutableListOf(-7L,7L,1L)),
    Param(0xD2D9, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2DC, true, PTP_DT.UINT32, formflag = Formflag.Range, enums = mutableListOf(0x00000000L,0xFFFFFFFFL,1L)),
    Param(0xD2DD, true, PTP_DT.INT8, formflag = Formflag.Range, enums = mutableListOf(-1L,1L,1L)),
    Param(0xD2DF, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2E0, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2E1, true, PTP_DT.UINT32, formflag = Formflag.Range, enums = mutableListOf(0x00000000L,0xFFFFFFFFL,1L)),
    Param(0xD2E2, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L,0x11L,0x12L)),
    Param(0xD2E3, true, PTP_DT.INT16, formflag = Formflag.Range, enums = mutableListOf(-32768L,32767L,1L)),
    Param(0xD2E4, true, PTP_DT.UINT32, formflag = Formflag.Range, enums = mutableListOf(0x00000000L,0xFFFFFFFFL,1L)),
    Param(0xD2E5, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2E6, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2E7, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2E9, true, PTP_DT.UINT8, formflag = Formflag.Range, enums = mutableListOf(0x00L,0xFFL,1L)),
    Param(0xD2EA, true, PTP_DT.UINT8, formflag = Formflag.Range, enums = mutableListOf(0x00L,0xFFL,1L)),
    Param(0xD2EB, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2EC, true, PTP_DT.INT16, formflag = Formflag.Range, enums = mutableListOf(-30L,30L,1L)),
    Param(0xD2ED, true, PTP_DT.INT16, formflag = Formflag.Range, enums = mutableListOf(-198L,198L,1L)),
    Param(0xD2EE, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2EF, true, PTP_DT.INT8, formflag = Formflag.Range, enums = mutableListOf(-1L,1L,1L)),
    Param(0xD2F0, true, PTP_DT.INT16, formflag = Formflag.Range, enums = mutableListOf(-1L,1L,1L)),
    Param(0xD2F1, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2F2, true, PTP_DT.UINT16, formflag = Formflag.Range, enums = mutableListOf()),
    Param(0xD2F3, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2F6, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2F7, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2F8, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2F9, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2FA, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2FB, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2FC, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2FD, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2FE, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD2FF, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD300, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD301, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD302, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD303, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD304, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD305, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD306, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD307, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD309, true, PTP_DT.UINT32, formflag = Formflag.Range, enums = mutableListOf()),
    Param(0xD30A, true, PTP_DT.UINT32, formflag = Formflag.Range, enums = mutableListOf()),
    Param(0xD30B, true, PTP_DT.INT32, formflag = Formflag.Range, enums = mutableListOf()),
    Param(0xD30C, true, PTP_DT.INT32, formflag = Formflag.Range, enums = mutableListOf()),
    Param(0xD30D, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD30E, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD312, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD313, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD314, true, PTP_DT.STR, formflag = Formflag.None, enums = mutableListOf()),
    Param(0xD315, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xD316, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xF000, true, PTP_DT.INT16, formflag = Formflag.Range, enums = mutableListOf(-32768L,32767L,1L)),
    Param(0xF001, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xF002, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xF003, true, PTP_DT.INT16, formflag = Formflag.Range, enums = mutableListOf(-32767L,32767L,1L)),
    Param(0xF004, true, PTP_DT.INT16, formflag = Formflag.Range, enums = mutableListOf(-32767L,32767L,1L)),
    Param(0xF00C, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L,2L)),
    Param(0xF012, true, PTP_DT.UINT16, formflag = Formflag.Enum, enums = mutableListOf(1L)),
    Param(0xF015, true, PTP_DT.UINT16, formflag = Formflag.Range, enums = mutableListOf(0x0000L,0xFFFFL,1L)),
)

enum class PTP_DT(val raw: Int) {
    UNDEF(0x0000),

    INT8(0x0001),
    UINT8(0x0002),
    INT16(0x0003),
    UINT16(0x0004),
    INT32(0x0005),
    UINT32(0x0006),
    INT64(0x0007),
    UINT64(0x0008),
    INT128(0x0009),
    UINT128(0x000A),
    AINT8(0x4001),
    AUINT8(0x4002),
    AINT16(0x4003),
    AUINT16(0x4004),
    AINT32(0x4005),
    AUINT32(0x4006),
    AINT64(0x4007),
    AUINT64(0x4008),
    AINT128(0x4009),
    AUINT128(0x400A),
    STR(0xFFFF);

    companion object { fun fromRaw(value: Int) = entries.firstOrNull { it.raw == value } ?: UNDEF }
}

enum class PTPContainerType(val raw: Int) {
    Command(0x0001),
    Data(0x0002),
    Response(0x0003),
    Event(0x0004);

    companion object { fun fromRaw(value: Int) = entries.firstOrNull { it.raw == value } ?: Response }
}

enum class PTP_OC(val raw: Int) {
    GetDeviceInfo(0x1001),
    OpenSession(0x1002),
    CloseSession(0x1003),
    GetStorageID(0x1004),
    GetStorageInfo(0x1005),
    GetNumObjects(0x1006),
    GetObjectHandles(0x1007),
    GetObjectInfo(0x1008),
    GetObject(0x1009),
    GetThumb(0x100A),
    SendObject(0x100D),
    GetPartialObject(0x101B),
    GetObjectPropValue(0x9803),
    GetObjectPropList(0x9805),

    SDIO_Connect(0x9201),
    SDIO_GetExtDeviceInfo(0x9202),
    SDIO_SetExtDevicePropValue(0x9205),
    SDIO_ControlDevice(0x9207),
    SDIO_GetAllExtDevicePropInfo(0x9209),
    SDIO_SetFTPSettingFilePassword(0x920F),
    SDIO_OpenSession(0x9210),
    SDIO_GetPartialLargeObject(0x9211),
    SDIO_SetContentsTransferMode(0x9212),
    SDIO_GetDisplayStringList(0x9215),
    SDIO_GetVendorCodeVersion(0x9216),
    SDIO_GetFTPJobList(0x9217),
    SDIO_ControlFTPJobList(0x9218),
    SDIO_UploadData(0x921A),
    SDIO_ControlUploadData(0x921B),
    SDIO_DownloadData(0x921D),
    SDIO_GetFTPSettingList(0x921F),
    SDIO_SetFTPSettingList(0x9220),
    SDIO_ControlGeneralSettingFile(0x9221),
    SDIO_GetControlGeneralSettingResultFile(0x9222),
    SDIO_GetLensInformation(0x9223),
    SDIO_RequestFirmwareUpdateCheck(0x9227),
    SDIO_SetFirmwareUpdateMode(0x9228),
    SDIO_UploadPartialData(0x9229),
    SDIO_ExecuteEFraming(0x922A),
    SDIO_OperationResultsSupported(0x922F),
    SDIO_GetPresetInfoList(0x9231),
    SDIO_GetDisplayFTPResult(0x9233),
    SDIO_GetOSDImage(0x9238),
    SDIO_GetRestrictionInfo(0x9239),
    SDIO_GetDeviceDescriptionFile(0x923A),
    SDIO_GetCapturedDateList(0x923B),
    SDIO_GetContentInfoList(0x923C),
    SDIO_GetContentData(0x923D),
    SDIO_GetContentCompressedData(0x923E),
    SDIO_GetStreamSettingList(0x9241),
    SDIO_SetStreamSettingList(0x9242),
    SDIO_ControlPTZF(0x9245),
    SDIO_SetPresetPTZF(0x9246),
    SDIO_GetFirmwareUpdateInfo(0x9247),
    SDIO_GetAreaTimeZoneSetting(0x9248),
    SDIO_SetAreaTimeZoneSetting(0x9249),
    SDIO_GetLicenseInfoList(0x924D),
    SDIO_DeleteContent(0x9250),
    SDIO_GetExtDeviceProp(0x9251);
}

enum class PTP_SDIE(val raw: Int) {
    UNDEF(0x0000),

    ObjectAdded(0xC201),
    ObjectRemoved(0xC202),
    DevicePropChanged(0xC203),
    DateTimeSettingResult(0xC205),
    CapturedEvent(0xC206),
    CWBCapturedResult(0xC208),
    CameraSettingReadResult(0xC209),
    FTPSettingReadResult(0xC20A),
    MediaFormatResult(0xC20B),
    ContentsTransferEvent(0xC20D),
    ZoomandFocusPositionEvent(0xC20E),
    DisplayListChangedEvent(0xC20F),
    MediaProfileChanged(0xC210),
    ControlJobListEvent(0xC211),
    ControlUploadDataResult(0xC214),
    ZoomPositionResult(0xC217),
    FocusPositionResult(0xC218),
    ControlGeneralSettingResult(0xC21A),
    LensInformationChanged(0xC21B),
    FirmwareUpdateCheckResult(0xC21D),
    FirmwareUpdateEvent(0xC21E),
    StreamStatusEvent(0xC21F),
    OperationResults(0xC222),
    AFStatus(0xC223),
    MovieRecOperationResults(0xC224),
    PresetInfoListChanged(0xC226),
    CautionDisplayEvent(0xC228),
    ContentInfoListChanged(0xC234),
    ControlPTZFResult(0xC238),
    PresetPTZFEvent(0xC239),
    DeleteContentResult(0xC240);

    companion object { fun fromRaw(value: Int) = entries.firstOrNull { it.raw == value } }
}

enum class PTP_CC(val raw: Int) {
    UNDEF(0x0000),

    S1_Button(0xD2C1),
    S2_Button(0xD2C2),
    AEL_Button(0xD2C3),
    Movie_Rec_Button_Hold(0xD2C8),
    FEL_Button(0xD2C9),
    Remote_Key_UP(0xD2CD),
    Remote_Key_DOWN(0xD2CE),
    Remote_Key_LEFT(0xD2CF),
    Remote_Key_RIGHT(0xD2D0),
    Near_Far(0xD2D1),
    AWBL_Button(0xD2D9),
    AF_Area_Position_xy(0xD2DC),
    Zoom_Operation(0xD2DD),
    Custom_WB_Capture_Standby(0xD2DF),
    Custom_WB_Capture_Standby_Cancel(0xD2E0),
    Custom_WB_Capture(0xD2E1),
    Selected_Media_Format(0xD2E2),
    High_Resolution_SS_Adjust(0xD2E3),
    Remote_Touch_Operation_xy(0xD2E4),
    Cancel_Remote_Touch_Operation(0xD2E5),
    S1_S2_Button(0xD2E6),
    Cancel_Media_Format(0xD2E7),
    Save_Zoom_and_Focus_Position(0xD2E9),
    Load_Zoom_and_Focus_Position(0xD2EA),
    APS_C_or_Full_Switching(0xD2EB),
    Color_Temperature_Step(0xD2EC),
    White_Balance_Tint_Step(0xD2ED),
    Reset_Multi_Matrix(0xD2EE),
    Focus_Operation(0xD2EF),
    High_Resolution_SS_Adjust_In_Integral_Multiples(0xD2F0),
    Flicker_Scan(0xD2F1),
    Set_PresetInfo_ZoomOnly_Value(0xD2F2),
    REC_Settings_Reset(0xD2F3),
    ContShootSpotBoost_Button(0xD2F6),
    Remote_Key_Cancel_Back_Button(0xD2F7),
    Remote_Key_Display_Button(0xD2F8),
    Remote_Key_SET(0xD2F9),
    Remote_Key_RIGHT_UP(0xD2FA),
    Remote_Key_RIGHT_DOWN(0xD2FB),
    Remote_Key_LEFT_UP(0xD2FC),
    Remote_Key_LEFT_DOWN(0xD2FD),
    Movie_Rec_Button_2nd_Toggle(0xD2FE),
    Remote_Key_Menu_Button(0xD2FF),
    Pixel_Mapping(0xD300),
    Power_Off(0xD301),
    Time_Code_Preset_Reset(0xD302),
    User_Bit_Preset_Reset(0xD303),
    Sensor_Cleaning(0xD304),
    Reset_Picture_Profile(0xD305),
    Reset_Creative_Look(0xD306),
    Stream_Button(0xD307),
    Camera_Button_Function(0xD309),
    Camera_Button_Function_Multi(0xD30A),
    Camera_Dial_Function(0xD30B),
    Camera_Lever_Function(0xD30C),
    Tracking_On_AF_On_Button(0xD30D),
    Forced_File_Number_Reset(0xD30E),
    Set_PostView_Enable(0xD312),
    Set_LiveView_Enable(0xD313),
    Create_New_Folder_still(0xD314),
    Camera_Standby(0xD315),
    Power_On(0xD316),
    Shutter_ECS_Number_Step(0xF000),
    Movie_Rec_Button_Toggle(0xF001),
    Cancel_Focus_Position(0xF002),
    Zoom_Operation_with_INT16(0xF003),
    Focus_Operation_with_INT16(0xF004),
    Cancel_Zoom_Position(0xF00C),
    USB_Connection_Mode_Request(0xF012),
    Preset_PTZF_Recall(0xF015);

    companion object { fun fromRaw(value: Int) = entries.firstOrNull { it.raw == value } }
}

enum class DPC(val raw: Int) {
    UNDEF(0x0000),

    White_Balance(0x5005),
    F_Number(0x5007),
    Focus_Mode(0x500A),
    Exposure_Metering_Mode(0x500B),
    Flash_Mode(0x500C),
    Exposure_Program_Mode(0x500E),
    Exposure_Bias_Compensation(0x5010),
    Still_Capture_Mode(0x5013),
    T_Number(0xD000),
    Iris_Mode_Setting(0xD001),
    Iris_Close_Setting(0xD002),
    Iris_Display_Unit(0xD003),
    Focal_Distance_in_Meter(0xD004),
    Focal_Distance_in_Feet(0xD005),
    Focal_Distance_Unit_Setting(0xD006),
    Focus_Mode_Setting(0xD007),
    Focus_Speed_Range(0xD008),
    Digital_Zoom_Scale(0xD00A),
    Zoom_Distance(0xD00B),
    White_Balance_Mode_Setting(0xD00C),
    White_Balance_Tint(0xD00D),
    Shutter_Angle(0xD00E),
    Shutter_Setting(0xD00F),
    Shutter_Mode(0xD010),
    Shutter_Mode_Status(0xD011),
    Shutter_Select_Mode(0xD012),
    Shutter_Mode_Setting(0xD013),
    Shutter_Slow(0xD014),
    Shutter_Slow_Frames(0xD015),
    Shutter_Speed_Value(0xD016),
    Shutter_Speed_Current_Value(0xD017),
    ND_Filter(0xD018),
    ND_Filter_Mode(0xD019),
    ND_Filter_Mode_Setting(0xD01A),
    ND_Filter_Value(0xD01B),
    Gain_Control_Setting(0xD01C),
    Gain_Unit_Setting(0xD01D),
    Gain_dB_Value(0xD01E),
    Gain_dB_Current_Value(0xD01F),
    Gain_Base_ISO_Sensitivity(0xD020),
    Gain_Base_Sensitivity(0xD021),
    Exposure_Index(0xD022),
    ISO_Current_Sensitivity(0xD023),
    Recording_Resolution_for_Main_Movie(0xD024),
    Recording_Resolution_for_Proxy_Movie(0xD025),
    Proxy_File_Format_Movie(0xD027),
    Recording_Frame_Rate_Proxy_Setting_Movie(0xD028),
    Zoom_Distance_Unit_Setting(0xD029),
    Sync_ID_for_FTP_Job_List(0xD02A),
    Media_SLOT1_Rec_Available_Type(0xD02B),
    Media_SLOT2_Rec_Available_Type(0xD02C),
    Select_FTP_ServerID(0xD02E),
    Movie_Playing_State(0xD02F),
    Movie_Playing_Speed(0xD030),
    Media_SLOT1_ProfileUrl(0xD031),
    Media_SLOT2_ProfileUrl(0xD032),
    Media_SLOT1_Player(0xD035),
    Media_SLOT2_Player(0xD036),
    Battery_Remain_Display_Unit(0xD037),
    Battery_Remaining_in_Minutes(0xD038),
    Battery_Remaining_in_Voltage(0xD039),
    Power_Source(0xD03A),
    AWB(0xD03B),
    BaseLook_Value(0xD03C),
    DC_Voltage(0xD03E),
    Software_Version(0xD040),
    FTP_Function(0xD041),
    Playback_Media(0xD042),
    REC_Settings_Reset_Enable_Status(0xD043),
    Monitor_DISP_Mode_Candidates(0xD044),
    Monitor_DISP_Mode_Setting(0xD045),
    Monitor_DISP_Mode(0xD046),
    Touch_Operation(0xD047),
    Select_Finder_Monitor(0xD048),
    Auto_Power_OFF_Temperature(0xD049),
    Body_Key_Lock(0xD04A),
    Image_ID_Numerical_Value(0xD04B),
    Image_ID_String(0xD04C),
    Monitor_LUT_Setting_All_Line(0xD04D),
    Auto_FTP_Transfer(0xD04E),
    Auto_FTP_Transfer_Target(0xD04F),
    Simul_Rec_Setting(0xD050),
    S_Q_Mode_Setting(0xD051),
    S_Q_Frame_Rate(0xD052),
    Picture_Cache_Rec_Setting(0xD053),
    Picture_Cache_Rec_Size_and_Time(0xD054),
    Interval_REC_Movie_Time(0xD055),
    Interval_REC_Movie_Frames(0xD056),
    Upload_Dataset_Version(0xD057),
    BaseLookImport_Command_Version(0xD059),
    Push_Auto_Iris(0xD05B),
    Push_AGC(0xD05C),
    Push_Auto_ND_Filter(0xD05D),
    Push_Auto_Focus(0xD05E),
    Imager_Scan_Mode(0xD05F),
    Subject_Recognition_AF(0xD060),
    AF_Transition_Speed(0xD061),
    AF_Subj_Shift_Sens(0xD062),
    Recording_Resolution_For_RAW_Movie(0xD063),
    Touch_Function_in_MF(0xD064),
    Paint_Look_Master_Black(0xD065),
    Paint_Look_R_Black(0xD066),
    Paint_Look_B_Black(0xD067),
    Paint_Look_Knee_Setting(0xD068),
    Paint_Look_Auto_Knee(0xD069),
    Paint_Look_Knee_Point(0xD06A),
    Paint_Look_Knee_Slope(0xD06B),
    Paint_Look_Detail_Setting(0xD06C),
    Paint_Look_Detail_Level(0xD06D),
    ND_Filter_Switching_Setting(0xD073),
    ND_Filter_Preset_Select(0xD074),
    ND_Filter_Preset_1_Value(0xD075),
    ND_Filter_Preset_2_Value(0xD076),
    ND_Filter_Preset_3_Value(0xD077),
    Monitoring_Output_Display_SDI(0xD078),
    Monitoring_Output_Display_HDMI(0xD079),
    Camera_System_Error_Info(0xD07A),
    Lens_Model_Name(0xD07B),
    Lens_Serial_Number(0xD07C),
    Lens_Version_Number(0xD07D),
    Simul_Rec_Setting_Movie_Rec_Button(0xD07F),
    Displayed_Menu_Status(0xD080),
    White_Balance_Switch(0xD085),
    White_Balance_Preset_Color_Temperature(0xD086),
    White_Balance_R_Gain(0xD087),
    White_Balance_B_Gain(0xD088),
    White_Balance_Offset_Color_Temp_ATW(0xD089),
    White_Balance_Offset_Tint_ATW(0xD08A),
    BaseLookImport_Operation_Enable_Status(0xD08B),
    Language_Setting(0xD08F),
    Auto_Focus_Hold(0xD091),
    Image_ID_Numerical_Value_Setting(0xD092),
    Exposure_Ctrl_Type(0xD099),
    FTPSettingList_Operation_Enable_Status(0xD09A),
    Playback_Contents_Recording_Date_Time(0xD09C),
    Playback_Contents_Name(0xD09D),
    Playback_Contents_Number(0xD09E),
    Playback_Contents_Total_Number(0xD09F),
    Playback_Contents_Recording_Resolution(0xD0A0),
    Playback_Contents_Recording_Frame_Rate(0xD0A1),
    Playback_Contents_Recording_File_Format(0xD0A2),
    Playback_Contents_Gamma_Type(0xD0A4),
    White_Balance_Offset_Setting(0xD0A9),
    White_Balance_Offset_Color_Temp(0xD0AA),
    Focus_Bracket_Shooting_Status(0xD0AB),
    Video_Stream_Select(0xD0AC),
    Video_Stream_Codec(0xD0AD),
    Video_Stream_Resolution(0xD0AE),
    Video_Stream_Bit_Rate_Compression_Mode(0xD0B5),
    Camera_Operating_Mode(0xD0BC),
    Playback_View_Mode(0xD0BD),
    Firmware_Update_Command_Version(0xD0BF),
    Firmware_Update_Status(0xD0C0),
    Maximum_number_of_bytes(0xD0C1),
    BaseLook_Name_of_Playback(0xD0C3),
    BaseLook_Applied_of_Playback(0xD0C4),
    Type_C_Accessory_Mode(0xD0C5),
    Pixel_Mapping_Enable_Status(0xD0C6),
    Delete_UserBaseLook(0xD0C7),
    Select_UserBaseLook_to_Edit(0xD0C8),
    UserBaseLook_Input(0xD0C9),
    UserBaseLook_AE_Level_Offset(0xD0CA),
    Base_ISO_Switch_EI(0xD0CB),
    Select_BaseLook_to_Set_in_PPLUT(0xD0CC),
    Eframing_Scale_Auto(0xD0CD),
    Eframing_Speed_Auto(0xD0CE),
    Camera_Eframing(0xD0CF),
    S_Q_Rec_Frame_Rate(0xD0D0),
    S_Q_Record_Setting(0xD0D1),
    Audio_Recording(0xD0D2),
    Time_Code_Preset(0xD0D3),
    User_Bit_Preset(0xD0D4),
    Time_Code_Format(0xD0D5),
    Time_Code_Run(0xD0D6),
    Time_Code_Make(0xD0D7),
    User_Bit_Time_Rec(0xD0D8),
    Image_Stabilization_Steady_Shot(0xD0D9),
    Image_Stabilization_Steady_Shot_Movie(0xD0DA),
    Silent_Mode(0xD0DB),
    Silent_Mode_Aperture_Drive_in_AF(0xD0DC),
    Silent_Mode_Shutter_When_Power_OFF(0xD0DD),
    Silent_Mode_Auto_Pixel_Mapping(0xD0DE),
    Shutter_Type(0xD0DF),
    Picture_Profile_BlackLevel(0xD0E0),
    Picture_Profile_Gamma(0xD0E1),
    Picture_Profile_BlackGamma_Range(0xD0E2),
    Picture_Profile_BlackGamma_Level(0xD0E3),
    Picture_Profile_Knee_Mode(0xD0E4),
    Picture_Profile_Knee_AutoSet_MaxPoint(0xD0E5),
    Picture_Profile_Knee_AutoSet_Sensitivity(0xD0E6),
    Picture_Profile_Knee_ManualSet_Point(0xD0E7),
    Picture_Profile_Knee_ManualSet_Slope(0xD0E8),
    Picture_Profile_Color_Mode(0xD0E9),
    Picture_Profile_Saturation(0xD0EA),
    Picture_Profile_ColorPhase(0xD0EB),
    Picture_Profile_Color_Depth_Red(0xD0EC),
    Picture_Profile_Color_Depth_Green(0xD0ED),
    Picture_Profile_Color_Depth_Blue(0xD0EE),
    Picture_Profile_Color_Depth_Cyan(0xD0EF),
    Picture_Profile_Color_Depth_Magenta(0xD0F0),
    Picture_Profile_Color_Depth_Yellow(0xD0F1),
    Picture_Profile_Detail_Level(0xD0F2),
    Picture_Profile_Detail_Adjust_Mode(0xD0F3),
    Picture_Profile_Detail_Adjust_V_H_Balance(0xD0F4),
    Picture_Profile_Detail_Adjust_B_W_Balance(0xD0F5),
    Picture_Profile_Detail_Adjust_Limit(0xD0F6),
    Picture_Profile_Detail_Adjust_Crispening(0xD0F7),
    Picture_Profile_Detail_Adjust_Highlight_Detail(0xD0F8),
    Copy_Picture_Profile(0xD0F9),
    Creative_Look(0xD0FA),
    Creative_Look_Contrast(0xD0FB),
    Creative_Look_Highlights(0xD0FC),
    Creative_Look_Shadows(0xD0FD),
    Creative_Look_Fade(0xD0FE),
    Creative_Look_Saturation(0xD0FF),
    Creative_Look_Sharpness(0xD100),
    Creative_Look_Sharpness_Range(0xD101),
    Creative_Look_Clarity(0xD102),
    Custom_Look_Image_Style(0xD103),
    Time_Code_Preset_Reset_Enable_Status(0xD104),
    User_Bit_Preset_Reset_Enable_Status(0xD105),
    Sensor_Cleaning_Enable_Status(0xD106),
    Reset_Picture_Profile_Enable_Status(0xD107),
    Reset_Creative_Look_Enable_Status(0xD108),
    Proxy_Record_Setting(0xD109),
    Video_Stream_Adaptive_Rate_Control(0xD10E),
    Video_Stream_Resolution_Method(0xD10F),
    Stream_Cipher_Type(0xD113),
    Stream_Latency(0xD116),
    Stream_TTL(0xD117),
    Stream_Mode_Setting(0xD118),
    Stream_Status(0xD119),
    Video_Stream_Movie_Rec_Permission(0xD11A),
    Audio_Stream_Codec_Type(0xD11B),
    Audio_Stream_Sampling_Frequency(0xD11C),
    Audio_Stream_Bit_Depth(0xD11D),
    Audio_Stream_Channel(0xD11E),
    Interval_REC_Movie_Count_Down_Interval_Time(0xD11F),
    Recording_Duration(0xD120),
    Eframing_Type(0xD122),
    Eframing_Command_Version(0xD123),
    Eframing_Mode_Auto(0xD124),
    Eframing_Speed_PTZ(0xD127),
    Second_Battery_Remaining(0xD12D),
    Second_Battery_Level_Indicator(0xD12E),
    ContShootSpotBoostSpeed(0xD12F),
    ContShootSpotBoost_Status(0xD130),
    ContShootSpotBoost_Enable_Status(0xD131),
    Select_IPTC_Metadata(0xD132),
    Flicker_Less_Shooting(0xD133),
    Flicker_Less_Shooting_Status(0xD134),
    Custom_WB_Size_Setting(0xD135),
    AF_Free_Size_and_Position_Setting(0xD138),
    Paint_Look_User_Matrix_Setting(0xD139),
    Paint_Look_User_Matrix_Level(0xD13A),
    Paint_Look_User_Matrix_Phase(0xD13B),
    Paint_Look_User_Matrix_R_G(0xD13C),
    Paint_Look_User_Matrix_R_B(0xD13D),
    Paint_Look_User_Matrix_G_R(0xD13E),
    Paint_Look_User_Matrix_G_B(0xD13F),
    Paint_Look_User_Matrix_B_R(0xD140),
    Paint_Look_User_Matrix_B_G(0xD141),
    Paint_Look_Multi_Matrix_Setting(0xD142),
    Paint_Look_Multi_Matrix_Axis(0xD143),
    Paint_Look_Multi_Matrix_Hue(0xD144),
    Paint_Look_Multi_Matrix_Saturation(0xD145),
    CompRAW_Shooting_NR(0xD148),
    CompRAW_Shooting_NR_RAW_File_Type(0xD149),
    FTP_Transfer_Still_Quality_Size(0xD14A),
    FTP_Transfer_Target_Proxy(0xD14B),
    FTP_Power_Save(0xD14C),
    ISO_Auto_Min_Shutter_Speed_Mode(0xD14D),
    ND_Filter_Unit_Setting(0xD14E),
    ND_Filter_Optical_Density_Value(0xD14F),
    USB_Power_Supply(0xD150),
    Interval_REC_Movie_Frame_Rate(0xD151),
    Interval_REC_Movie_Record_Setting(0xD152),
    Eframing_Recording_Image_Crop(0xD153),
    Eframing_HDMI_Crop(0xD154),
    Synchroterminal_Forced_Output(0xD155),
    Shutter_Release_Time_Lag_Control(0xD156),
    Subject_Recognition_in_AF(0xD157),
    Recognition_Target(0xD158),
    Right_Left_Eye_Select(0xD159),
    CompRAW_Shooting_NR_Number_of_Sheets(0xD15A),
    Long_Exposure_NR(0xD15B),
    High_ISO_NR(0xD15C),
    HLG_Still_Image(0xD15D),
    Color_Space_Still_Image(0xD15E),
    Recording_Media_Still_Image(0xD15F),
    Recording_Media_Movie(0xD160),
    Auto_Switch_Media(0xD161),
    Continuous_Shooting_Speed_in_Electric_Shutter_Hiplus(0xD162),
    Continuous_Shooting_Speed_in_Electric_Shutter_Hi(0xD163),
    Continuous_Shooting_Speed_in_Electric_Shutter_Mid(0xD164),
    Continuous_Shooting_Speed_in_Electric_Shutter_Lo(0xD165),
    Bracket_order(0xD166),
    Focus_Bracket_order(0xD167),
    Focus_Bracket_Exposure_Lock_1st_Img(0xD168),
    Focus_Bracket_Interval_Until_Next_Shot(0xD169),
    Interval_REC_Still_Shooting_Start_Time(0xD16A),
    Interval_REC_Still_Shooting_Interval(0xD16B),
    Interval_REC_Still_Number_of_Shots(0xD16C),
    Interval_REC_Still_AE_Tracking_Sensitivity(0xD16D),
    Interval_REC_Still_Shutter_Type(0xD16E),
    Interval_REC_Still_Shoot_Interval_Priority(0xD16F),
    e_Front_Curtain_Shutter(0xD170),
    Wind_Noise_Reduct(0xD171),
    Audio_Level_Display(0xD172),
    Auto_Slow_Shutter(0xD173),
    ISO_Auto_Min_Shutter_Speed_Manual(0xD176),
    ISO_Auto_Min_Shutter_Speed_Preset(0xD177),
    Soft_Skin_Effect(0xD178),
    Priority_Set_in_AF_S(0xD179),
    Priority_Set_in_AF_C(0xD17A),
    Focus_Magnification_Time(0xD17B),
    Playback_Volume_Settings(0xD17C),
    Auto_Review(0xD17D),
    Audio_Signals(0xD17E),
    HDMI_Resolution_Still_Play(0xD17F),
    HDMI_Output_Rec_Media_Movie(0xD180),
    HDMI_Output_Resolution_Movie(0xD181),
    HDMI_Output_4K_Set_Movie(0xD182),
    HDMI_Output_RAW_Movie(0xD183),
    HDMI_Output_Raw_Setting_Movie(0xD184),
    HDMI_Output_Color_Gamut_for_RAW_Out_Movie(0xD185),
    HDMI_Output_Time_Code_Movie(0xD186),
    HDMI_Output_REC_Control_Movie(0xD187),
    TimeShift_Shooting(0xD189),
    TimeShift_Trigger_Setting(0xD18A),
    TimeShift_PreShooting_Time_Setting(0xD18B),
    Top_of_the_Group_Shooting_Mark_Setting(0xD18C),
    Media_SLOT3_Status(0xD18E),
    Media_SLOT3_Remaining_shooting_time(0xD18F),
    Media_SLOT3_Rec_Available_Type(0xD190),
    Media_SLOT3_ProfileUrl(0xD191),
    Image_Stabilization_Steady_Shot_Adjust(0xD192),
    Image_Stabilization_Steady_Shot_Focal_Length(0xD193),
    Camera_Shake_Status(0xD194),
    Update_Body_Status(0xD195),
    Embed_LUT_File(0xD196),
    Media_SLOT1_Writing_State(0xD197),
    Media_SLOT2_Writing_State(0xD198),
    Auto_FTP_Transfer_Target_Movie(0xD199),
    FTP_Transfer_Target(0xD19A),
    TimeShift_Shooting_Status(0xD19B),
    Focus_Driving_Status_Absolute(0xD19C),
    Zoom_Driving_Status_Absolute(0xD19D),
    Default_AF_Free_Size_and_Position_Setting(0xD19E),
    Extended_Shutter_Speed(0xD19F),
    Lens_Compensation_Shading(0xD1A2),
    Lens_Compensation_Chromatic_Aberration(0xD1A3),
    Lens_Compensation_Distortion(0xD1A4),
    Lens_Compensation_Breathing(0xD1A5),
    Focus_Bracket_Recording_Folder(0xD1A6),
    Release_without_Lens(0xD1A7),
    Release_without_Card(0xD1A8),
    Image_Stabilization_Framing_Stabilizer(0xD1A9),
    Priority_Set_in_AWB(0xD1AA),
    AF_Illuminator(0xD1AB),
    Aperture_Drive_in_AF(0xD1AC),
    AF_with_Shutter(0xD1AD),
    Full_Time_DMF(0xD1AE),
    Pre_AF(0xD1AF),
    Display_Quality_Finder_Monitor(0xD1B0),
    Audio_Signals_Volume(0xD1B1),
    Control_for_HDMI(0xD1B2),
    Anti_dust_Shutter_When_Power_Off(0xD1B3),
    Shooting_Self_timer_Status(0xD1B4),
    Metered_Manual_Level(0xD1B5),
    ISO_Auto_Range_Limit_min(0xD1B6),
    ISO_Auto_Range_Limit_max(0xD1B7),
    Face_Eye_Frame_Display(0xD1B8),
    AF_in_Focus_Magnifier(0xD1BA),
    Camera_Error_Caution_Status(0xD1BB),
    System_Error_Caution_Status(0xD1BC),
    Initial_Focus_Magnifier_Still(0xD1BD),
    Remote_Save_Image_Size(0xD1BE),
    Program_Shift_Status(0xD1BF),
    Wake_on_LAN(0xD1C1),
    Tracking_On_AF_On_Enable_Status(0xD1C6),
    APS_C_Super_35mm_Shooting(0xD1C7),
    Recording_File_Number_Still(0xD1C8),
    Forced_File_Number_Reset_Enable_Status(0xD1C9),
    Recording_Setting_File_Name(0xD1CA),
    Recording_Folder_Format(0xD1CB),
    StreamSettingList_Operation_Enable_Status(0xD1CC),
    Write_Copyright_Info(0xD1CD),
    Set_Photographer(0xD1CE),
    Set_Copyright(0xD1CF),
    File_Settings_Camera_ID(0xD1D0),
    File_Settings_Reel_Number(0xD1D1),
    File_Settings_Camera_Position(0xD1D2),
    ContentInfoList_Enable_Status_SLOT1(0xD1D4),
    ContentInfoList_Enable_Status_SLOT2(0xD1D5),
    ContentInfoList_regenerate_time_SLOT1(0xD1D6),
    ContentInfoList_regenerate_time_SLOT2(0xD1D7),
    PostView_Transfer_Resource_Status(0xD1DA),
    Create_New_Folder_Still_Enable_Status(0xD1DB),
    File_Settings_Title_Name_Settings(0xD1DC),
    Microphone_directivity(0xD1DD),
    Grid_Line_Display(0xD1DE),
    Product_Showcase_Set(0xD1DF),
    Amount_of_Defocus_Setting(0xD1E0),
    Cinematic_Vlog_Setting(0xD1E1),
    Cinematic_Vlog_Look(0xD1E2),
    Cinematic_Vlog_Mood(0xD1E3),
    Cinematic_Vlog_AF_Transition_Speed(0xD1E4),
    Face_Priority_in_Multi_Metering(0xD1E5),
    Subject_Recognition_Person_Tracking_Subject_Shift_Range(0xD1E6),
    Subject_Recognition_Animal_Bird_Priority(0xD1E7),
    Subject_Recognition_Animal_Bird_Detection_Parts(0xD1E8),
    Subject_Recognition_Animal_Still_Tracking_Subject_Shift_Range(0xD1E9),
    Subject_Recognition_Animal_Still_Tracking_Sensitivity(0xD1EA),
    Subject_Recognition_Animal_Still_Detection_Sensitivity(0xD1EB),
    Subject_Recognition_Animal_Still_Detection_Parts(0xD1EC),
    Subject_Recognition_Bird_Tracking_Subject_Shift_Range(0xD1ED),
    Subject_Recognition_Bird_Tracking_Sensitivity(0xD1EE),
    Subject_Recognition_Bird_Detection_Sensitivity(0xD1EF),
    Subject_Recognition_Bird_Detection_Parts(0xD1F0),
    Subject_Recognition_Insect_Tracking_Subject_Shift_Range(0xD1F1),
    Subject_Recognition_Insect_Tracking_Sensitivity(0xD1F2),
    Subject_Recognition_Insect_Detection_Sensitivity(0xD1F3),
    Subject_Recognition_Car_Train_Tracking_Subject_Shift_Range(0xD1F4),
    Subject_Recognition_Car_Train_Tracking_Sensitivity(0xD1F5),
    Subject_Recognition_Car_Train_Detection_Sensitivity(0xD1F6),
    Subject_Recognition_Plane_Tracking_Subject_Shift_Range(0xD1F7),
    Subject_Recognition_Plane_Tracking_Sensitivity(0xD1F8),
    Subject_Recognition_Plane_Detection_Sensitivity(0xD1F9),
    Subject_Recognition_Priority_on_registered_face(0xD1FA),
    Monitor_Brightness_Type(0xD1FB),
    Monitor_Brightness_Manual(0xD1FC),
    TC_UB_Display_Setting(0xD1FD),
    Gamma_Display_Assist(0xD1FE),
    Gamma_Display_Assist_Type(0xD1FF),
    Flash_Compensation(0xD200),
    Dynamic_Range_Optimizer(0xD201),
    Image_Size(0xD203),
    Total_Battery_Remaining(0xD204),
    Total_Battery_Level_Indicator(0xD205),
    OSD_Image_Mode(0xD207),
    Camera_Button_Function_capability(0xD208),
    Camera_Button_Function_Multi_capability(0xD209),
    Camera_Dial_Function_capability(0xD20A),
    Camera_Lever_Function_capability(0xD20B),
    Camera_Button_Function_Status(0xD20C),
    Shutter_Speed(0xD20D),
    Battery_Level_Indicator(0xD20E),
    Color_Temperature(0xD20F),
    Biaxial_Fine_Tuning_G_M_Direction(0xD210),
    Aspect_Ratio(0xD211),
    Focus_Indication(0xD213),
    Predicted_Maximum_File_Size(0xD214),
    Shooting_File_Info(0xD215),
    Auto_FTP_Transfer_Target_Still(0xD216),
    AELock_Indication(0xD217),
    Battery_Remaining(0xD218),
    Picture_Effect(0xD21B),
    Biaxial_Fine_Tuning_A_B_Direction(0xD21C),
    Movie_Recording_State(0xD21D),
    ISO_Sensitivity(0xD21E),
    FELock_Indication(0xD21F),
    Audio_Signals_Start_End(0xD220),
    Live_View_Status(0xD221),
    Still_Image_Save_Destination(0xD222),
    Date_Time_Setting(0xD223),
    Protect_Image_in_FTP_Transfer(0xD225),
    Auto_Recognition_Target_Candidates(0xD229),
    Focus_Area(0xD22C),
    Live_View_Display_Effect(0xD231),
    Auto_Recognition_Target_Setting(0xD234),
    Near_Far_Enable_Status(0xD235),
    Exposure_Step(0xD237),
    Pixel_Shift_Shooting_Mode(0xD239),
    Pixel_Shift_Shooting_Number(0xD23A),
    Pixel_Shift_Shooting_Interval(0xD23B),
    Pixel_Shift_Shooting_Status(0xD23C),
    Progress_Number_of_Pixel_Shift_Shooting(0xD23D),
    Picture_Profile(0xD23F),
    Creative_Style(0xD240),
    File_Format_Movie(0xD241),
    Recording_Setting_Movie(0xD242),
    Media_SLOT1_Status(0xD248),
    Media_SLOT1_Remaining_number_shots(0xD249),
    Media_SLOT1_Remaining_shooting_time(0xD24A),
    Focal_position(0xD24C),
    AWBLock_Indication(0xD24E),
    Interval_REC_Still_Mode(0xD24F),
    Interval_REC_Still_Status(0xD250),
    Device_Overheating_State(0xD251),
    Still_Image_Quality(0xD252),
    File_Format_Still(0xD253),
    Focus_Magnifier_Setting(0xD254),
    AF_Tracking_Sensitivity_Still(0xD255),
    Media_SLOT2_Status(0xD256),
    Media_SLOT2_Remaining_number_shots(0xD257),
    Media_SLOT2_Remaining_shooting_time(0xD258),
    Position_Key_Setting(0xD25A),
    Zoom_Operation_Enable_Status(0xD25B),
    Zoom_Scale(0xD25C),
    Zoom_Bar_Information(0xD25D),
    Zoom_Speed_Range(0xD25E),
    Zoom_Setting(0xD25F),
    Zoom_Type_Status(0xD260),
    Wireless_Flash_Setting(0xD262),
    Red_Eye_Reduction(0xD263),
    Remote_Control_Restriction_Status(0xD264),
    Live_View_Area_xy(0xD267),
    Still_Image_Trans_Size(0xD268),
    RAW_J_PC_Save_Image(0xD269),
    Live_View_Image_Quality(0xD26A),
    Custom_WB_Capturable_Area_xy(0xD26B),
    Custom_WB_Capture_Frame_Size_xy(0xD26C),
    Custom_WB_Capture_Standby_Operation(0xD26D),
    Custom_WB_Capture_Standby_Cancel_Operation(0xD26E),
    Custom_WB_Capture_Operation(0xD26F),
    Custom_WB_Execution_State(0xD270),
    Camera_Setting_Save_Operation(0xD271),
    Camera_Setting_Read_Operation(0xD272),
    Camera_Setting_Save_Read_State(0xD273),
    FTP_Setting_Save_Operation(0xD274),
    FTP_Setting_Read_Operation(0xD275),
    FTP_Setting_Save_Read_State(0xD276),
    LiveViewURL(0xD278),
    Media_SLOT1_Format_Enable_Status(0xD279),
    Media_SLOT2_Format_Enable_Status(0xD27A),
    Media_Format_Progress_Rate(0xD27B),
    Select_FTP_Server(0xD27C),
    FTP_Connection_Status(0xD27F),
    FTP_Connection_Error_Info(0xD280),
    High_Resolution_SS_Setting(0xD281),
    High_Resolution_Shutter_Speed(0xD282),
    Function_of_Touch_Operation(0xD283),
    Remote_Touch_Operation_Enable_Status(0xD284),
    Cancel_Remote_Touch_Operation_Enable_Status(0xD285),
    Recording_Frame_Rate_Setting_Movie(0xD286),
    Compression_File_Format_Still(0xD287),
    RAW_File_Type(0xD288),
    Media_Slot1_RAW_File_Type(0xD289),
    Media_Slot2_RAW_File_Type(0xD28A),
    Media_Slot1_File_Format_Still(0xD28B),
    Media_Slot2_File_Format_Still(0xD28C),
    Media_SLOT1_Image_Quality(0xD28D),
    Media_SLOT2_Image_Quality(0xD28E),
    Media_SLOT1_Image_Size(0xD28F),
    Media_SLOT2_Image_Size(0xD290),
    Media_SLOT1_Quick_Format_Enable_Status(0xD292),
    Media_SLOT2_Quick_Format_Enable_Status(0xD293),
    Cancel_Media_Format_Enable_Status(0xD294),
    Contents_Transfer_Enable_Status(0xD295),
    Save_Zoom_and_Focus_Position(0xD297),
    Load_Zoom_and_Focus_Position(0xD298),
    Remote_Control_Zoom_Speed_Type(0xD299),
    APS_C_or_Full_Switching_Setting(0xD29A),
    APS_C_or_Full_Switching_Enable_Status(0xD29B),
    Movie_Rec_Self_timer(0xD29C),
    Movie_Rec_Self_timer_Count_time(0xD29D),
    Paint_Look_Multi_Matrix_Area_Indication(0xD29E),
    Movie_Rec_Self_timer_Continuous(0xD29F),
    Movie_Rec_Self_timer_Status(0xD2A0),
    Focus_Bracket_Shot_Num(0xD2A1),
    Focus_Bracket_Focus_Range(0xD2A2),
    Bulb_Timer_Setting(0xD2A4),
    Bulb_Exposure_Time_Setting(0xD2A5),
    Elapsed_Bulb_Exposure_Time(0xD2A6),
    Remaining_Bulb_Exposure_Time(0xD2A7),
    Remaining_Noise_Reduction_Time(0xD2A8),
    Monitor_LUT_Setting_Output_Dest_Assign(0xD2A9),
    Monitor_LUT_Setting_1(0xD2AA),
    Monitor_LUT_Setting_2(0xD2AB),
    Monitor_LUT_Setting_3(0xD2AC),
    AF_Track_for_Speed_Change(0xD2AD),
    Monitoring_Output_Display_Setting_Dest_Assign(0xD2AE),
    Monitoring_Output_Display_Setting_1(0xD2AF),
    Monitoring_Output_Display_Setting_2(0xD2B0),
    UserBaseLook_Output(0xD2B1),
    Play_Set_of_Multi_Media(0xD2B2),
    Video_Stream_Bit_Rate_VBR_Mode(0xD2B3),
    Recording_File_Number_Movie(0xD2B5),
    Flicker_Scan_Status(0xD2BA),
    Flicker_Scan_Enable_Status(0xD2BB),
    Tele_Wide_Lever_Value_capability(0xD2BD),
    Target_Streaming_Destination_Select(0xD2BE),
    Stream_Display_Name(0xD2BF),
    Video_Stream_Max_Bit_Rate(0xD2C0),
    Movie_Shooting_Mode(0xE000),
    Movie_Shooting_Mode_Color_Gamut(0xE001),
    Movie_Shooting_Mode_Target_Display(0xE002),
    Focus_TouchSpot_Status(0xE004),
    Focus_Tracking_Status(0xE005),
    Shutter_ECS_Setting(0xE006),
    Shutter_ECS_Number(0xE007),
    Shutter_ECS_Frequency(0xE008),
    Depth_of_Field_Adjustment_Mode(0xE009),
    Depth_of_Field_Adjustment_Interlocking_Mode_State(0xE00A),
    Recorder_Clip_Name(0xE00B),
    Recorder_Control_Main_Setting(0xE00C),
    Recorder_Control_Proxy_Setting(0xE00D),
    Recorder_Start_Main(0xE00E),
    Recorder_Start_Proxy(0xE00F),
    Recorder_Main_Status(0xE010),
    Recorder_Proxy_Status(0xE011),
    Recorder_Ext_Raw_Status(0xE012),
    Recorder_Save_Destination(0xE013),
    Button_Assignment_Assignable_1(0xE014),
    Button_Assignment_Assignable_2(0xE015),
    Button_Assignment_Assignable_3(0xE016),
    Button_Assignment_Assignable_4(0xE017),
    Button_Assignment_Assignable_5(0xE018),
    Button_Assignment_Assignable_6(0xE019),
    Button_Assignment_Assignable_7(0xE01A),
    Button_Assignment_Assignable_8(0xE01B),
    Button_Assignment_Assignable_9(0xE01C),
    Button_Assignment_Assignable_10(0xE01D),
    Button_Assignment_LensAssignable_1(0xE01E),
    SceneFile_Index(0xE01F),
    Current_SceneFile_Edited(0xE020),
    Movie_Play_Button(0xE021),
    Movie_Play_Pause_Button(0xE022),
    Movie_Play_Stop_Button(0xE023),
    Movie_Forward_Button(0xE024),
    Movie_Rewind_Button(0xE025),
    Movie_Next_Button(0xE026),
    Movie_Prev_Button(0xE027),
    Movie_RecReview_Button(0xE028),
    Assignable_Button_1(0xE029),
    Assignable_Button_2(0xE02A),
    Assignable_Button_3(0xE02B),
    Assignable_Button_4(0xE02C),
    Assignable_Button_5(0xE02D),
    Assignable_Button_6(0xE02E),
    Assignable_Button_7(0xE02F),
    Assignable_Button_8(0xE030),
    Assignable_Button_9(0xE031),
    Assignable_Button_10(0xE032),
    LensAssignable_Button_1(0xE033),
    Assignable_Button_Indicator_1(0xE035),
    Assignable_Button_Indicator_2(0xE036),
    Assignable_Button_Indicator_3(0xE037),
    Assignable_Button_Indicator_4(0xE038),
    Assignable_Button_Indicator_5(0xE039),
    Assignable_Button_Indicator_6(0xE03A),
    Assignable_Button_Indicator_7(0xE03B),
    Assignable_Button_Indicator_8(0xE03C),
    Assignable_Button_Indicator_9(0xE03D),
    Assignable_Button_Indicator_10(0xE03E),
    LensAssignable_Button_Indicator_1(0xE03F),
    Zoom_Position_Setting(0xE040),
    Zoom_Position_Current_Value(0xE041),
    Focus_Position_Setting(0xE042),
    Focus_Position_Current_Value(0xE043),
    Focus_Mode_status(0xE044),
    Focus_Operation_with_INT16_Enable_Status(0xE045),
    Audio_Input_CH1_Level_Control(0xE048),
    Audio_Input_CH2_Level_Control(0xE049),
    Audio_Input_CH3_Level_Control(0xE04A),
    Audio_Input_CH4_Level_Control(0xE04B),
    Audio_Input_CH1_Level(0xE04C),
    Audio_Input_CH2_Level(0xE04D),
    Audio_Input_CH3_Level(0xE04E),
    Audio_Input_CH4_Level(0xE04F),
    Audio_Input_Master_Level(0xE050),
    Audio_Input_CH1_Input_Select(0xE051),
    Audio_Input_CH2_Input_Select(0xE052),
    Audio_Input_CH3_Input_Select(0xE053),
    Audio_Input_CH4_Input_Select(0xE054),
    Audio_Input_CH1_Wind_Filter(0xE055),
    Audio_Input_CH2_Wind_Filter(0xE056),
    Audio_Input_CH3_Wind_Filter(0xE057),
    Audio_Input_CH4_Wind_Filter(0xE058),
    Audio_Output_HDMI_Monitor_CH(0xE059),
    Pan_Tilt_Acceleration_Ramp_Curve(0xE05C),
    Remote_Key_Thumbnail_Button(0xE05F),
    Remote_Key_SLOT_Select_Button(0xE060),
    Movie_Rec_Button_Toggle_Enable_Status(0xE061),
    Video_Rec_Format_Bitrate_Setting(0xE067),
    Valid_Rec_Video_Format(0xE068),
    Monitoring_Output_Format(0xE06C),
    AF_Area_Position_xy_AF_C(0xE079),
    Image_Stabilization_Level_Movie(0xE080),
    Control_General_SettingFile_Enable_Status(0xE081),
    Movie_Trimming_Transfer_Support_Information(0xE082),
    Function_of_Remote_Touch_Operation(0xE083),
    AF_Assist(0xE084),
    Lens_Information_Enable_Status(0xE086),
    Follow_Focus_Position_Setting(0xE088),
    Follow_Focus_Position_Current_Value(0xE089),
    Button_Assignment_Assignable_11(0xE08D),
    Assignable_Button_11(0xE08E),
    Assignable_Button_Indicator_11(0xE08F),
    Focus_Speed_Direct_Sync(0xE092),
    Movie_Quality_FullAuto_Mode(0xE0A0),
    De_Squeeze_Display_Ratio(0xE0A4),
    IR_Remote_Setting(0xE0A5),
    IP_Setup_Protocol_Setting(0xE0A6),
    Movie_Rec_Review_Playing_State(0xE07A),
    Audio_Input1_Type_Select(0xE0AA),
    Audio_Input2_Type_Select(0xE0AB),
    Camera_Power_Status(0xE0AF),
    Recordable_Power_Sources(0xE0B0),
    Video_Rec_Format_Quality(0xE0B5),
    Pan_Position_Current_Value(0xE0B6),
    Pan_Position_Status(0xE0B7),
    Tilt_Position_Current_Value(0xE0B8),
    Tilt_Position_Status(0xE0B9),
    Pan_Limit_Range_Minimum(0xE0BA),
    Pan_Limit_Range_Maximum(0xE0BB),
    Tilt_Limit_Range_Minimum(0xE0BC),
    Tilt_Limit_Range_Maximum(0xE0BD),
    Pan_Limit_Mode(0xE0BE),
    Tilt_Limit_Mode(0xE0BF),
    ControlPTZF_Binary_Version(0xE0C0),
    Preset_PTZF_Number_of_Slots(0xE0CB),
    SetPresetPTZF_Binary_Version(0xE0CC),
    Enlarge_Screen_Setting(0xE0CD),
    Live_View_Image_Quality_by_Numerical_Value(0xE0CE),
    Red_Tally_Lamp_Control(0xE0D2),
    Green_Tally_Lamp_Control(0xE0D3),
    Yellow_Tally_Lamp_Control(0xE0D4),
    Debug_Mode(0xE0D5),
    Wind_Noise_Reduct_for_External_Mic(0xE0D6),
    Noise_Cut_Filter(0xE0D7),
    Noise_Cut_Filter_for_External_Mic(0xE0D8),
    ContentInfoList_update_time_SLOT1(0xE0D9),
    ContentInfoList_update_time_SLOT2(0xE0DA),
    CompRAW_Shooting_HDR(0xE0DB),
    CompRAW_Shooting_HDR_DR_Setting(0xE0DC),
    CompRAW_Shooting_HDR_RAW_File_Type(0xE0DD),
    CompRAW_Shooting_HDR_Number_of_Sheets(0xE0DE),
    Call_Setting(0xE0E1),
    Manual_Input_for_ND_Filter_Value(0xE0E2),
    Log_Shooting_Mode_Still(0xE0E3),
    Log_Shooting_Mode_Color_Gamut_Still(0xE0E4),
    ND_Filter_Position_Setting(0xE0E5),
    SceneFile_Command_Version(0xE0E6),
    Eframing_Tracking_Start_Mode(0xE0F0),
    Eframing_Production_Effect(0xE0F1),
    DeleteContent_Operation_Enable_Status_SLOT1(0xE0F3),
    DeleteContent_Operation_Enable_Status_SLOT2(0xE0F4),
    Different_Set_for_S_Q_Mv(0xE0F5),
    Angle_of_view_Priority_Movie(0xE0F6),
    Eframing_Auto_Framing(0xE0F8),
    SceneFile_Indexes_Available_for_Download(0xE0F9),
    Shooting_Enable_Setting_License(0xE0FA),
    Maximum_Size_of_Image_ID_String(0xE0FE),
    Digital_Extender_Magnification_Setting(0xE100),
    SceneFile_Upload_Operation_Enable_Status(0xE101),
    SceneFile_Download_Operation_Enable_Status(0xE102),
    Monitor_DISP_Mode_Candidates_Still(0xE107),
    Monitor_DISP_Mode_Setting_Still(0xE108),
    Monitor_DISP_Mode_Still(0xE109),
    Monitor_DISP_Mode_Candidates_Movie(0xE10A),
    Monitor_DISP_Mode_Setting_Movie(0xE10B),
    Monitor_DISP_Mode_Movie(0xE10C),
    Grid_Line_Display_Playback(0xE10E),
    Grid_Line_Type(0xE10F),
    CustomGridLineFile_Command_Version(0xE110),
    Home_Menu_Setting_Lower_Left(0xE111),
    Stream_Button_Enable_Status(0xE112),
    Peaking_Display(0xE11A),
    Peaking_Level(0xE11B),
    Peaking_Color(0xE11C),
    Zebra_Display(0xE11D),
    Zebra_Level(0xE11E),
    Zebra_Level_Type_Custom(0xE11F),
    Zebra_Level_Standard_Custom(0xE120),
    Zebra_Level_Range_Custom(0xE121),
    Zebra_Level_Lower_Limit_Custom(0xE122),
    Marker_Display(0xE123),
    Center_Marker_Display(0xE124),
    Aspect_Marker_Ratio_Movie(0xE125),
    Safety_Zone_Display(0xE126),
    Guideframe_Display(0xE127);

    companion object { fun fromRaw(value: Int) = entries.firstOrNull { it.raw == value } ?: UNDEF }
}

// FNumber
// type: CrDataType_UInt16
// value = F number * 100
enum class CrFnumber(val raw: Int) {
    IrisClose(0xFFFD), // Iris Close
    Unknown  (0xFFFE), // Display "--"
    Nothing  (0xFFFF); // Nothing to display
}

// ExposureBiasCompensation
// type: CrDataType_UInt16
// value: compensation value * 1000

// ShutterSpeed
// type: CrDataType_UInt32
// value: upper two bytes = numerator lower two bytes = denominator.
enum class CrShutterSpeed(val raw: Long) {
    Bulb(0x00000000),
    Nothing(0xFFFFFFFF); // Nothing to display
}

// IsoSensitivity
// type: CrDataType_UInt32
// value: bit 28-31 extension bit 24-27 ISO mode bit 0-23 ISO value
enum class CrISO(val raw: Int) {
    Normal(0x00 ),           // ISO setting Normal
    MultiFrameNR(0x01),      // Multi Frame NR
    MultiFrameNR_High(0x02), // Multi Frame NR High
    Ext(0x10),               // Indicates of extended value
    AUTO(0xFFFFFF);
}

fun describeDpOrCc(code: Int): String {
    DPC.fromRaw(code).takeIf { it != DPC.UNDEF }?.let { return it.name }
    PTP_CC.fromRaw(code)?.let { return it.name }
    return "(unknown)"
}
